test

diff --git a/.github/workflows/NipunLakshyaApp.yml b/.github/workflows/NipunLakshyaApp.yml
--- a/.github/workflows/NipunLakshyaApp.yml
+++ b/.github/workflows/NipunLakshyaApp.yml
@@ -23,9 +23,6 @@ jobs:
       - name: Install Appium
         run: npm install -g appium
 
-      - name: Start appium server
-        run: appium --address 0.0.0.0 --port 4723 &
-
       - name: Enable KVM group perms
         run: |
           echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
@@ -61,4 +58,15 @@ jobs:
             adb shell input keyevent 82  
             adb devices
             sleep 10
+            appium --address 0.0.0.0 --port 4723 > /dev/null 2>&1 &
+            sleep 10
             npm test
+            TEST_EXIT_CODE=$?
+            echo "Stopping Appium server running on port 4723"
+            PID=$(lsof -ti :4723)
+            if [ -n "$PID" ]; then
+              kill $PID || echo "Failed to kill Appium process on port 4723"
+            else
+              echo "No process found running on port 4723"
+            fi
+            exit $TEST_EXIT_CODE
